# Generated by Django 4.0.4 on 2022-06-24 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('NFSDATA', '0003_category_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
