# Generated by Django 4.0.4 on 2022-06-24 17:28

import NFSDATA.formatchecker
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NFSDATA', '0004_subcategory_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_amount', models.IntegerField()),
                ('product_cost_price', models.FloatField()),
                ('product_image', NFSDATA.formatchecker.ContentRestrictiononFileField(default=None, upload_to='media/')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NFSDATA.category')),
                ('product_subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NFSDATA.subcategory')),
            ],
        ),
    ]
