# Generated by Django 4.0.4 on 2022-06-26 03:47

import NFSDATA.formatchecker
from django.db import migrations, models
import nepali_datetime_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('NFSDATA', '0005_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='NepaliCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date_custom', nepali_datetime_field.models.NepaliDateField()),
                ('date_auto_add', nepali_datetime_field.models.NepaliDateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=NFSDATA.formatchecker.ContentRestrictiononFileField(default=None, upload_to='products/'),
        ),
    ]
