# Generated by Django 4.0.4 on 2022-06-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFSDATA', '0006_nepalicustom_alter_products_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nepalicustom',
            name='date_auto_add',
        ),
    ]
