# Generated by Django 4.0.4 on 2022-06-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_category_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
